In [2]:
import pandas as pd

In [9]:
df=pd.read_csv('Training.csv')
df1=pd.read_csv('Testing.csv')

In [10]:
df1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,9,120,72,22,56,20.8,0.733,48,0
1,1,71,62,0,0,21.8,0.416,26,0
2,8,74,70,40,49,35.3,0.705,39,0
3,5,88,78,30,0,27.6,0.258,37,0
4,10,115,98,0,0,24.0,1.022,34,0
...,...,...,...,...,...,...,...,...,...
303,10,101,76,48,180,32.9,0.171,63,0
304,2,122,70,27,0,36.8,0.340,27,0
305,5,121,72,23,112,26.2,0.245,30,0
306,1,126,60,0,0,30.1,0.349,47,1
307,1,93,70,31,0,30.4,0.315,23,0

In [11]:
x_train=df.drop(columns='Outcome')
y_train=df['Outcome']
x_test=df1.drop(columns='Outcome')
y_test=df1['Outcome']

In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score

In [18]:
dtc=DecisionTreeClassifier()
dtc.fit(x_test,y_test)
predict=dtc.predict(x_test)
print(f1_score(y_test,predict))

1.0

NameError: name 'Print' is not defined